const {test}=require('node:test');const assert=require('node:assert/strict');const M=require('../cat-merge/model');const Art=require('../cat-merge/cats');const fs=require('node:fs');const path=require('node:path');
function state(board){return {board,score:0,moves:0,merges:0,highest:Math.max(1,...board),next:1,status:M.status(board)};}
function rng(seed){return ()=>((seed=(Math.imul(seed,1664525)+1013904223)>>>0)/4294967296);}
test('initial garden has adjacent pairs, room, and valid state',()=>{const s=M.create();assert.equal(s.board.filter(Boolean).length,6);assert.equal(s.highest,1);assert.ok(M.pairs(s.board).length);assert.ok(M.valid(s));});
test('all eleven merges produce exactly the next evolution and correct score without mutating input',()=>{for(let rank=1;rank<12;rank++){const b=Array(16).fill(0);b[5]=b[6]=rank;const s=state(b), before=JSON.stringify(s),r=M.act(s,5,6,()=>.5);assert.equal(r.state.board[6],rank+1);assert.equal(r.points,2**rank*10);assert.equal(r.state.score,r.points);assert.equal(r.state.highest,rank+1);assert.equal(JSON.stringify(s),before);assert.ok(M.valid(r.state));assert.equal(r.state.status,rank===11?'won':'playing');assert.equal(r.arrival===null,rank===11);}});
test('row edges and diagonals are not neighbors; mismatches and invalid actions do not advance',()=>{assert.equal(M.adjacent(3,4),false);assert.equal(M.adjacent(0,5),false);const s=M.create();for(const [a,b]of [[0,15],[0,0],[-1,2],[0,16],[.5,1],[2,3]])assert.equal(M.act(s,a,b),null);const b=Array(16).fill(0);b[0]=1;b[1]=2;assert.equal(M.act(state(b),0,1),null);});
test('moving consumes one free space with no points, merging preserves occupancy',()=>{let s=M.create();let r=M.act(s,0,3,()=>.5);assert.equal(r.merged,false);assert.equal(r.state.board.filter(Boolean).length,7);assert.equal(r.state.score,0);assert.equal(r.state.moves,1);r=M.act(s,5,6,()=>.5);assert.equal(r.state.board.filter(Boolean).length,6);assert.ok(r.arrival);});
test('full board remains playable with a neighboring pair; ends without one',()=>{let b=Array.from({length:16},(_,i)=>(Math.floor(i/4)+i%4)%2+1);assert.equal(M.status(b),'over');assert.equal(M.act(state(b),0,1),null);b[1]=1;assert.equal(M.status(b),'playing');const r=M.act(state(b),0,1,()=>.5);assert.ok(r);assert.equal(r.state.board.filter(Boolean).length,16);assert.ok(M.valid(r.state));});
test('a real final move can fill the garden and trigger game over',()=>{const b=Array.from({length:16},(_,i)=>(Math.floor(i/4)+i%4)%2+1);b[0]=0;const s=state(b);const r=M.act(s,2,0,()=>.99);assert.equal(r.state.status,'over');});
test('arrival tiers accelerate within bounds based on round highest',()=>{for(let h=1;h<=12;h++)for(const n of [0,.69,.7,.999]){const tier=M.next(h,()=>n);assert.ok(tier>=1&&tier<=8&&tier<=Math.max(1,h-3));}});
test('saved state validation rejects malformed, stale and impossible shapes',()=>{const s=M.create();assert.ok(M.valid(JSON.parse(JSON.stringify(s))));for(const patch of [{board:[1]},{score:-1},{moves:NaN},{highest:13},{next:12},{status:'won'},{board:Array(16).fill(0)}])assert.equal(M.valid({...s,...patch}),false);});
test('seeded legal games preserve invariants and always have an action while playing',()=>{for(let seed=1;seed<=150;seed++){const random=rng(seed);let s=M.create(random);for(let step=0;step<600&&s.status==='playing';step++){const pairs=M.pairs(s.board),empty=s.board.map((v,i)=>v?null:i).filter(v=>v!==null),filled=s.board.map((v,i)=>v?i:null).filter(v=>v!==null);const action=pairs.length&&random()<.85?pairs[Math.floor(random()*pairs.length)]:empty.length?[filled[Math.floor(random()*filled.length)],empty[Math.floor(random()*empty.length)]]:pairs[0];assert.ok(action);const r=M.act(s,...action,random);assert.ok(r);assert.ok(M.valid(r.state));assert.ok(r.state.score>=s.score);s=r.state;}assert.ok(['playing','over','won'].includes(s.status));}});
test('every evolution has distinct original art; locked art does not reveal its identity',()=>{const portraits=Array.from({length:12},(_,i)=>Art.svg(i+1));assert.equal(new Set(portraits).size,12);assert.equal(Art.svg(1,true),Art.svg(12,true));assert.ok(!portraits.some(s=>/https?:/.test(s)));});
test('landing metadata, static guide, homepage entry, sitemap and relative links',()=>{const root=path.resolve(__dirname,'..'),html=fs.readFileSync(path.join(root,'cat-merge/index.html'),'utf8');assert.equal((html.match(/<h1>/g)||[]).length,1);assert.ok(html.includes('<h1>Cat Merge</h1>'));assert.ok(html.includes('rel="canonical" href="https://puzzleten.com/cat-merge/"'));assert.ok(!/noindex/i.test(html));const schema=JSON.parse(html.match(/<script type="application\/ld\+json">([\s\S]*?)<\/script>/)[1]);assert.equal(schema['@type'],'VideoGame');for(const title of ['How to Play Cat Merge','Discover Every Cat','Cat Merge Tips','About Cat Merge','Cat Merge FAQ'])assert.ok(html.includes(title));for(const m of html.matchAll(/(?:href|src)="([^"#]+)"/g)){if(/^https?:/.test(m[1]))continue;assert.ok(fs.existsSync(path.resolve(m[1].startsWith('/')?root:path.join(root,'cat-merge'),m[1].replace(/^\//,''))),m[1]);}assert.ok(fs.readFileSync(path.join(root,'sitemap.xml'),'utf8').includes('https://puzzleten.com/cat-merge/'));assert.ok(fs.readFileSync(path.join(root,'index.html'),'utf8').includes('href="cat-merge/"'));});

test("every third merge gives breathing room without an arrival",()=>{const s=M.create();s.moves=2;s.merges=2;const r=M.act(s,5,6,()=>.5);assert.equal(r.breather,true);assert.equal(r.arrival,null);assert.equal(r.state.board.filter(Boolean).length,5);assert.ok(M.valid(r.state));});

test("complete seeded play reaches the final cat through legal moves from the starting garden",()=>{let counts={},wins=0,max=0,longest=0;for(let seed=1;seed<=20;seed++){let n=seed;const rnd=()=>((n=(Math.imul(n,1664525)+1013904223)>>>0)/4294967296);let s=M.create(rnd);for(let i=0;i<3000&&s.status==='playing';i++){const pairs=M.pairs(s.board);let action;if(pairs.length){pairs.sort((a,b)=>s.board[b[0]]-s.board[a[0]]);const [a,b]=pairs[0];const level=s.board[a]+1;const neighbors=x=>s.board.reduce((sum,v,j)=>sum+(v===level&&M.adjacent(x,j)?1:0),0);action=neighbors(a)>neighbors(b)?[b,a]:[a,b];}else{let choices=[];for(let a=0;a<16;a++)if(s.board[a])for(let b=0;b<16;b++)if(!s.board[b]){let matches=s.board.reduce((sum,v,j)=>sum+(j!==a&&v===s.board[a]&&M.adjacent(b,j)?1:0),0);choices.push({a,b,weight:matches*100+s.board[a]});}choices.sort((a,b)=>b.weight-a.weight);if(!choices.length)break;action=[choices[0].a,choices[0].b];}s=M.act(s,...action,rnd).state;longest=Math.max(longest,i);}max=Math.max(max,s.highest);counts[s.highest]=(counts[s.highest]||0)+1;assert.equal(s.status,'won','seed '+seed+' did not finish');assert.ok(s.moves<300);if(s.status==='won')wins++;}assert.equal(wins,20);});
