(async()=>{
  const root=document.getElementById('fixture'),M=CatMergeModel;let passed=0,failed=0,game;const errors=[];window.addEventListener('error',e=>errors.push(e.message));
  const assert=(v,message)=>{if(!v)throw Error(message||'Assertion failed');};
  const memory=()=>{const data={};return {getItem:k=>data[k]??null,setItem:(k,v)=>data[k]=v};};
  function fresh(storage=memory()){game?.destroy();game=new CatMergeGame(root,{random:()=>.5,storage,discoveryMs:0});return game;}
  const pause=()=>new Promise(r=>setTimeout(r,10));
  async function test(name,fn){const li=document.createElement('li');try{await fn();li.textContent='PASS: '+name;passed++;}catch(e){li.textContent='FAIL: '+name+' — '+e.message;failed++;}document.getElementById('checks').append(li);}
  await test('tap pair merges, highlights selection, announces discovery and unlocks portrait',async()=>{const g=fresh();g.cells[5].click();assert(g.cells[5].getAttribute('aria-pressed')==='true');assert(g.cells[6].classList.contains('is-match'));g.cells[6].click();assert(g.state.board[6]===2);assert(g.state.score===20);assert(g.$('message').textContent.includes('New cat discovered'));assert(g.discovered.includes(2));await pause();assert(!g.cells[6].disabled);});
  await test('non-neighbor does not consume a move; empty-space move adds a cat',()=>{const g=fresh();g.choose(0);g.choose(15);assert(g.state.moves===0);g.choose(3);assert(g.state.moves===1);assert(g.state.board.filter(Boolean).length===7);});
  await test('best score, collection, tutorial and active round restore',async()=>{const storage=memory(),g=fresh(storage);g.play(5,6);await pause();const before=JSON.stringify(g.state);const restored=fresh(storage);assert(JSON.stringify(restored.state)===before);assert(restored.discovered.includes(2));assert(restored.best===20);assert(restored.taught);});
  await test('restart resets round but preserves collection and best; confirmation can be cancelled',async()=>{const g=fresh();g.play(5,6);await pause();g.$('restart').click();assert(g.$('confirm').open);g.$('cancel').click();assert(g.state.score===20);g.$('restart').click();g.$('new').click();assert(!g.$('confirm').open);assert(g.state.score===0);assert(g.best===20);assert(g.discovered.includes(2));assert(document.activeElement===g.cells[5]);});
  await test('corrupt or blocked local storage does not prevent play',()=>{for(const storage of [{getItem:()=>'{oops',setItem:()=>{}},{getItem:()=>{throw Error('blocked');},setItem:()=>{throw Error('blocked');}}]){const g=fresh(storage);assert(M.valid(g.state));assert(g.play(5,6));}});
  await test('every evolution reveals correct name and persists, including final completion',async()=>{const g=fresh();for(let rank=1;rank<12;rank++){const board=Array(16).fill(0);board[5]=board[6]=rank;g.state={board,score:0,moves:0,merges:0,highest:rank,next:1,status:'playing'};g.render();assert(g.play(5,6));assert(g.discovered.includes(rank+1));assert(g.$('discovery').textContent.includes(M.NAMES[rank]));await pause();}assert(g.state.status==='won');assert(!g.$('result').hidden);assert(g.$('progress').textContent==='12 / 12');g.$('again').click();assert(g.state.status==='playing');assert(g.discovered.length===12);});
  await test('loss shows score and highest cat, disables board, Play Again works',()=>{const g=fresh(),board=Array.from({length:16},(_,i)=>(Math.floor(i/4)+i%4)%2+1);board[0]=0;g.state={board,score:90,moves:1,merges:0,highest:2,next:1,status:'playing'};g.render();g.play(2,0);assert(g.state.status==='over');assert(!g.$('result').hidden);assert(g.$('summary').textContent.includes('Playful Kitten'));assert(g.cells.every(c=>c.disabled));g.$('again').click();assert(g.state.status==='playing');assert(g.$('result').hidden);});
  await test('arrow navigation and Escape preserve accessible selection semantics',()=>{const g=fresh();g.cells[5].focus();g.choose(5);g.cells[5].dispatchEvent(new KeyboardEvent('keydown',{key:'ArrowRight',bubbles:true}));assert(document.activeElement===g.cells[6]);g.cells[6].dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true}));assert(g.selected===null);assert(g.cells.every(c=>c.getAttribute('aria-pressed')==='false'));});
  await test('touch-pointer drag and cancellation use the same merge rules',async()=>{const g=fresh();g.$('board').scrollIntoView({block:'center'});const a=g.cells[5].getBoundingClientRect(),b=g.cells[6].getBoundingClientRect();const e=(type,x,y)=>new PointerEvent(type,{pointerId:7,pointerType:'touch',isPrimary:true,button:0,clientX:x,clientY:y,bubbles:true});const capture=g.cells[5].setPointerCapture;g.cells[5].setPointerCapture=()=>{};g.cells[5].dispatchEvent(e('pointerdown',a.x+10,a.y+10));g.cells[5].dispatchEvent(e('pointermove',b.x+b.width/2,b.y+b.height/2));assert(!!g.ghost);g.cells[5].dispatchEvent(e('pointerup',b.x+b.width/2,b.y+b.height/2));g.cells[5].setPointerCapture=capture;assert(g.state.board[6]===2);assert(!g.ghost);await pause();const moves=g.state.moves;g.pointer={id:8,from:0,x:0,y:0,moved:true};g.$('board').dispatchEvent(new PointerEvent('pointercancel',{pointerId:8,bubbles:true}));assert(g.state.moves===moves);assert(!g.pointer);});
  await test('compact board and collection fit a 280px container with usable touch targets',()=>{const g=fresh();root.style.width='280px';g.$('collection').open=true;assert(root.scrollWidth<=root.clientWidth+1,'horizontal overflow');assert(g.cells.every(c=>c.getBoundingClientRect().width>=44),'small target');root.style.width='';});
  await test('page ran without uncaught errors',()=>assert(errors.length===0,errors.join('; ')));
  document.getElementById('results').textContent=`${passed} passed, ${failed} failed`;document.title=`Cat Merge: ${passed} passed, ${failed} failed`;
})();
