const test=require('node:test'),assert=require('node:assert/strict'),M=require('../color-pop/model.js');
const seeded=()=>{let n=731;return ()=>((n=(n*1664525+1013904223)>>>0)/4294967296);};
function state(bubbles){const s=M.create(1,seeded());s.board=new Map(bubbles.map(([r,c,color])=>[M.key(r,c),{r,c,color}]));s.current=0;s.next=0;return s;}
test('original levels stay connected, within walls and above danger',()=>{for(let level=1;level<=30;level++){const s=M.create(level,seeded());assert.equal(M.detached(s).length,0);assert.equal(s.goal,Math.min(75,30+(level-1)*5));for(const b of s.board.values()){const p=M.center(b.r,b.c,s.phase);assert(p.x>=M.R&&p.x<=M.W-M.R);assert(p.y+M.R<M.DANGER);}}});
test('hex neighbors are reciprocal across both row phases',()=>{for(const phase of [0,1])for(let r=0;r<12;r++)for(let c=0;M.valid(r,c,phase);c++)for(const [a,b] of M.neighbors(r,c,phase)){assert(M.neighbors(a,b,phase).some(([x,y])=>x===r&&y===c));const p=M.center(r,c,phase),q=M.center(a,b,phase);assert(Math.abs(Math.hypot(p.x-q.x,p.y-q.y)-40)<1e-7);}});
test('matching three pops whole group and drops disconnected bubbles with bonus',()=>{const s=state([[0,0,0],[0,1,0],[1,0,1],[1,1,1]]);const result=M.resolve(s,{r:0,c:2},seeded());assert.equal(result.popped.length,3);assert.equal(result.dropped.length,2);assert.equal(result.points,70);assert.equal(s.cleared,5);assert.equal(s.status,'won');});
test('two matching bubbles stay on board; consecutive matches earn combo bonus',()=>{const s=state([[0,0,0],[0,5,1],[0,6,1],[0,8,2]]);let result=M.resolve(s,{r:0,c:1},seeded());assert.equal(result.points,0);assert.equal(s.misses,1);s.current=0;result=M.resolve(s,{r:0,c:2},seeded());assert.equal(result.points,30);s.current=1;result=M.resolve(s,{r:0,c:7},seeded());assert.equal(result.points,45);assert.equal(s.combo,2);});
test('five misses add one row without moving old bubbles sideways',()=>{const s=state([[0,0,0]]);const before=M.center(0,0,s.phase);s.misses=4;s.current=1;const result=M.resolve(s,{r:0,c:1},seeded());assert(result.descended);const moved=s.board.get('1,0'),p=M.center(moved.r,moved.c,s.phase);assert.equal(p.x,before.x);assert.equal(p.y,before.y+M.DY);assert.equal(s.misses,0);assert.equal(M.detached(s).length,0);});
test('danger line loses; completed goal wins and blocks further changes',()=>{const s=state(Array.from({length:14},(_,r)=>[r,0,r%2]));s.current=3;M.resolve(s,{r:13,c:1});assert.equal(s.status,'lost');const w=state([[0,0,0],[0,1,0],[0,8,1]]);w.cleared=28;M.resolve(w,{r:0,c:2});assert.equal(w.status,'won');const score=w.score;assert.equal(M.resolve(w,{r:1,c:1}),null);assert.equal(w.score,score);});
test('trace hits ceiling, bounces at walls and finds empty adjacent landing cells',()=>{const s=state([]);for(const angle of [-Math.PI/2,-.23,-Math.PI+.23]){const t=M.trace(s,angle);assert(t.cell);assert.equal(t.cell.r,0);assert(t.path.every(p=>p.x>=M.R-1e-6&&p.x<=M.W-M.R+1e-6));if(angle!==-Math.PI/2)assert(t.path.length>2);}const filled=M.create(1,seeded());for(let a=-2.9;a<-.23;a+=.08){const t=M.trace(filled,a);assert(t.cell);assert(!filled.board.has(M.key(t.cell.r,t.cell.c)));assert(M.neighbors(t.cell.r,t.cell.c,filled.phase).some(([r,c])=>filled.board.has(M.key(r,c))));}});
test('many complete shots preserve geometry and only offer remaining colors',()=>{const random=seeded();for(let run=0;run<30;run++){const s=M.create(1+run%8,random);for(let n=0;n<150&&s.status==='playing';n++){const t=M.trace(s,-Math.PI+.23+random()*(Math.PI-.46));M.resolve(s,t.cell,random);if(s.status==='playing'){assert(M.colors(s).includes(s.current));assert(M.colors(s).includes(s.next));assert.equal(M.detached(s).length,0);}for(const b of s.board.values())assert(M.valid(b.r,b.c,s.phase));}}});
