(async()=>{
 const root=document.getElementById('fixture'),results=[];let game,events;
 const assert=(value,msg)=>{if(!value)throw Error(msg);};
 const seed=()=>{let n=741;return ()=>((n=(n*1664525+1013904223)>>>0)/4294967296);};
 function setup(){game?.destroy();events=[];game=new ColorPopGame(root,{random:seed(),analytics:name=>events.push(name)});}
 async function test(name,run){setup();const li=document.createElement('li');try{await run();li.className='pass';li.textContent='PASS: '+name;results.push(true);}catch(e){li.className='fail';li.textContent='FAIL: '+name+' — '+e.message;results.push(false);}document.getElementById('results').append(li);}
 function finishShot(){let now=performance.now();for(let i=0;game.shot&&i<200;i++){cancelAnimationFrame(game.raf);game.raf=0;game.lastFrame=now;now+=20;game.frame(now);}cancelAnimationFrame(game.raf);game.raf=0;assert(!game.shot,'shot never finished');}
 function preset(bubbles){game.state.board=new Map(bubbles.map(([r,c,color])=>[r+','+c,{r,c,color}]));game.state.current=0;game.state.next=0;}
 await test('level 1 starts with goal, score, current and next colors',()=>{assert(game.state.goal===30,'goal');assert(game.$('score').textContent==='0','score');assert(!game.$('fire').disabled,'fire disabled');assert(game.canvas.width>0,'canvas');});
 await test('aim buttons and keyboard change angle',()=>{const angle=game.angle;game.$('left').click();assert(game.angle<angle,'left');game.canvas.dispatchEvent(new KeyboardEvent('keydown',{key:'ArrowRight',bubbles:true,cancelable:true}));assert(game.angle>angle-.065,'keyboard');});
 await test('fire follows guide and permits only one projectile',()=>{const target=ColorPopModel.trace(game.state,game.angle).cell;const before=game.state.board.size;game.fire();const shot=game.shot;game.fire();assert(game.shot===shot,'double shot');finishShot();assert(game.state.board.size!==before,'no resolution');assert(events.filter(e=>e==='game_start').length===1,'start analytics');assert(!game.state.board.has(target.r+','+target.c)||game.state.board.get(target.r+','+target.c).color===shot.color,'wrong attachment');});
 await test('matching group and disconnected fall complete level and next level preserves score',()=>{preset([[0,0,0],[0,1,0],[1,0,1],[1,1,1]]);game.shot={cell:{r:0,c:2},x:100,y:24};game.settle();assert(game.state.status==='won','not won');assert(game.state.score===70,'wrong bonus');assert(!game.$('overlay').hidden,'overlay');assert(game.$('continue').textContent==='Next Level','next label');assert(events.includes('level_complete'),'completion analytics');game.$('continue').click();assert(game.state.level===2&&game.state.score===70,'progression');});
 await test('danger line displays loss and retry resets level',()=>{preset(Array.from({length:14},(_,r)=>[r,0,r%2]));game.state.current=3;game.shot={cell:{r:13,c:1},x:80,y:480};game.settle();assert(game.state.status==='lost','no loss');assert(events.includes('game_over'),'loss analytics');game.$('continue').click();assert(game.state.status==='playing'&&game.state.cleared===0,'retry');});
 await test('restart can be cancelled and confirmation clears projectile',()=>{game.fire();const board=game.state.board;game.$('restart').click();assert(game.$('dialog').open,'dialog');game.$('cancel').click();assert(game.state.board===board,'cancel reset');game.$('restart').click();game.$('confirm').click();assert(!game.shot&&game.state.cleared===0,'restart did not reset');});
 await test('touch pointer aims, cancellation does not fire, release fires',()=>{const c=game.canvas,r=c.getBoundingClientRect();c.setPointerCapture=()=>{};const send=type=>c.dispatchEvent(new PointerEvent(type,{pointerId:8,pointerType:'touch',button:0,clientX:r.left+r.width*.6,clientY:r.top+r.height*.5,bubbles:true}));send('pointerdown');send('pointercancel');send('pointerup');assert(!game.shot,'cancelled touch fired');send('pointerdown');send('pointerup');assert(game.shot,'touch release did not fire');finishShot();});
 await test('idle board has no animation loop and reduced motion resolves gameplay',()=>{assert(!game.raf,'idle loop');game.reduced=true;game.fire();finishShot();assert(!game.shot,'reduced motion stalled');});
 const failed=results.filter(x=>!x).length;document.getElementById('summary').textContent=`${results.length-failed} passed · ${failed} failed`;game.destroy();
})();
