(async()=>{
const root=document.getElementById('fixture'),assert=(v,m)=>{if(!v)throw Error(m);};let game,values={},events=[],results=[];
const key='puzzleten:dino-nestkeepers:v1',storage={getItem:k=>values[k]||null,setItem:(k,v)=>values[k]=v};
function setup(data={}){game?.destroy();values=data;events=[];game=new DinoGame(root,{auto:false,storage,random:()=>0,analytics:(name,p)=>events.push({name,...p})});}
async function test(name,run){setup();const li=document.createElement('li');try{await run();li.className='pass';li.textContent='PASS: '+name;results.push(true);}catch(e){li.className='fail';li.textContent='FAIL: '+name+' — '+e.message;results.push(false);}document.getElementById('results').append(li);}
function start(){if(game.mode==='tutorial')game.deliver(game.state.eggs[0].id,0);}
function match(type=0){game.state.eggs=[];const e=DinoModel.spawn(game.state,()=>0,type);game.render();game.deliver(e.id,type);}
await test('first visit is frozen practice, wrong answer is penalty free',()=>{assert(game.mode==='tutorial','no tutorial');const e=game.state.eggs[0];game.advance(10);assert(e.y===38,'practice moved');game.deliver(e.id,1);assert(game.state.lives===3&&game.state.score===0,'practice penalty');assert(events.every(e=>e.name!=='game_start'),'started early');});
await test('tutorial completion starts a fresh round and persists once completed',()=>{start();assert(game.mode==='play'&&!game.paused,'not playing');assert(game.state.score===0&&game.state.hatched===0,'tutorial awarded points');assert(JSON.parse(values[key]).tutorialDone,'completion not saved');assert(events.some(e=>e.name==='dino_tutorial_complete'),'no tutorial event');assert(events.filter(e=>e.name==='game_start').length===1,'start count');});
await test('returning player sees Play, not repeating tutorial',()=>{start();setup({...values});assert(game.mode==='ready'&&game.$('dialog').open,'returning state');game.$('dialog-actions').lastChild.click();assert(game.mode==='play','cannot start');});
await test('tap egg then nest works and highlights selected egg',()=>{start();const e=game.state.eggs[0],b=game.elements.get(e.id);b.click();assert(b.getAttribute('aria-pressed')==='true','selection invisible');game.$('nests').children[e.type].click();assert(game.state.correct===1&&game.state.score===10,'tap failed');});
await test('keyboard selection supports numbered nests',()=>{start();const e=game.state.eggs[0];game.elements.get(e.id).click();root.dispatchEvent(new KeyboardEvent('keydown',{key:String(e.type+1),bubbles:true,cancelable:true}));assert(game.state.correct===1,'keyboard failed');});
await test('third egg hatches, updates collection, saves best and emits discovery once',()=>{start();match();match();match();assert(game.state.hatched===1&&game.state.score===85,'hatch score');assert(game.prefs.discovered.includes(0),'discovery');assert(root.querySelector('.dn-reward'),'reward missing');assert(JSON.parse(values[key]).best===85,'best not saved');match();match();match();assert(events.filter(e=>e.name==='dino_species_discovered').length===1,'duplicate discovery');});
await test('unlock pauses before new species eggs arrive and keeps nest slots stable',()=>{start();const slots=[...game.$('nests').children];for(let i=0;i<9;i++)match();assert(game.state.active===4&&game.paused,'unlock not paused');assert(game.$('dialog-title').textContent==='A new nest is ready','unlock announcement');assert([...game.$('nests').children].every((b,i)=>b===slots[i]),'nests moved');game.$('dialog-actions').lastChild.click();assert(!game.paused,'resume failed');});
await test('pause and collection freeze time and eggs',()=>{start();const e=game.state.eggs[0],y=e.y;game.pause();game.advance(5);assert(e.y===y&&game.state.elapsed===0,'paused progressed');game.$('dialog-actions').lastChild.click();game.collection();game.advance(5);assert(e.y===y,'collection progressed');game.$('dialog-actions').lastChild.click();game.advance(.1);assert(e.y>y,'resume stalled');});
await test('resize cancels held egg and requires explicit resume',()=>{start();game.selected=game.state.eggs[0].id;game.onResize();assert(game.selected===null&&game.paused&&game.$('dialog').open,'resize lost safety');});
await test('replaying tutorial preserves score, lives and nest progress',()=>{start();match();const previous=game.state;game.tutorial();game.deliver(game.state.eggs[0].id,0);assert(game.state===previous&&game.state.score===10,'round lost');assert(game.paused,'resumed without user');game.$('dialog-actions').lastChild.click();assert(!game.paused,'resume');});
await test('wrong and missed eggs cost one life; game over is emitted once',()=>{start();const wrong=()=>{game.state.eggs=[];const e=DinoModel.spawn(game.state,()=>0,0);game.render();game.deliver(e.id,1);};wrong();assert(game.state.lives===2,'wrong life');game.state.eggs=[];const e=DinoModel.spawn(game.state,()=>0,0);e.y=99.9;game.advance(.1);assert(game.state.lives===1,'missed life');wrong();game.advance(.1);assert(game.mode==='over'&&game.$('dialog').open,'game over');assert(events.filter(e=>e.name==='game_over').length===1,'event count');assert(events.find(e=>e.name==='game_over').wrong_eggs===2,'aggregates');});
await test('play again resets run but retains collection and best',()=>{start();match();match();match();game.state.lives=0;game.state.status='over';game.gameOver();game.$('dialog-actions').lastChild.click();assert(game.state.score===0&&game.state.active===3&&game.state.lives===3,'round reset');assert(game.prefs.best===85&&game.prefs.discovered.includes(0),'collection lost');});
await test('saved discoveries restore and corrupt saves cannot break play',()=>{start();match();match();match();setup({...values});assert(game.prefs.best===85&&game.prefs.discovered.includes(0),'restore');setup({[key]:'{broken'});assert(game.mode==='tutorial','bad JSON');});
await test('blocked storage and analytics do not stop input',()=>{game.destroy();game=new DinoGame(root,{auto:false,random:()=>0,storage:{getItem(){throw Error();},setItem(){throw Error();}},analytics(){throw Error();}});start();match();assert(game.state.correct===1,'input broke');assert(!game.$('storage').hidden,'storage notice');});
await test('real browser storage keeps preferences across instances',()=>{const temp='puzzleten:dino-test:'+Date.now();const isolated={getItem:()=>localStorage.getItem(temp),setItem:(k,v)=>localStorage.setItem(temp,v)};try{game.destroy();game=new DinoGame(root,{auto:false,storage:isolated,random:()=>0});start();match();match();match();game.destroy();game=new DinoGame(root,{auto:false,storage:isolated});assert(game.prefs.best===85&&game.prefs.discovered.includes(0),'real restore');}finally{localStorage.removeItem(temp);}});
function drag(source,target,cancel=false){source.setPointerCapture=()=>{};const r=source.getBoundingClientRect();const send=(type,x,y)=>source.dispatchEvent(new PointerEvent(type,{bubbles:true,button:0,pointerType:'touch',pointerId:77,clientX:x,clientY:y,cancelable:true}));send('pointerdown',r.x+r.width/2,r.y+r.height/2);send('pointermove',target.x,target.y);send(cancel?'pointercancel':'pointerup',target.x,target.y);}
await test('touch drag uses actual nest hit test; cancelled drag costs no life',()=>{start();root.scrollIntoView();const e=game.state.eggs[0],b=game.elements.get(e.id),r=game.$('nests').children[0].getBoundingClientRect(),p={x:r.x+r.width/2,y:r.y+r.height/2};drag(b,p,true);assert(game.state.lives===3&&game.state.correct===0&&game.selected===null,'cancel changed round');drag(b,p);assert(game.state.correct===1,'drag did not match');});
await test('dropping outside nests releases egg without life loss',()=>{start();root.scrollIntoView();const e=game.state.eggs[0],b=game.elements.get(e.id),r=game.$('field').getBoundingClientRect();drag(b,{x:r.right-5,y:r.top+5});assert(game.state.eggs.length===1&&game.state.lives===3&&game.selected===null,'outside drop penalty');game.advance(.1);assert(e.y>0,'egg stayed frozen');});
await test('sound can be toggled and audio failure cannot break a match',()=>{game.destroy();let muted=true;game=new DinoGame(root,{auto:false,random:()=>0,storage,sound:{isMuted:()=>muted,setMuted:v=>{muted=v;},chain(){throw Error('blocked audio');}}});if(game.mode==='ready')game.$('dialog-actions').lastChild.click();else start();game.$('sound').click();assert(!muted&&game.$('sound').getAttribute('aria-pressed')==='true','mute toggle');match();assert(game.state.correct===1,'audio broke gameplay');});
const failed=results.filter(x=>!x).length;document.getElementById('summary').textContent=`${results.length-failed} passed · ${failed} failed`;game.destroy();
})();
