const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');
const D=require('../dress-up-game/data'),M=require('../dress-up-game/model'),A=require('../dress-up-game/art');
test('70 distinct original items and 15 themes have valid metadata and artwork',()=>{assert.equal(D.items.length,70);assert.equal(new Set(D.items.map(i=>i.id)).size,70);assert.equal(D.themes.length,15);for(const i of D.items){assert.ok(D.categories[i.category]);assert.match(i.color,/^#[0-9a-f]{6}$/i);assert.ok(i.tags.length>=3);assert.ok(A.item(i).includes('<path'));assert.ok(A.thumb(i).includes('<svg'));}assert.equal(D.skins.length,5);});
test('outfit slots replace correctly and dresses exclude separates',()=>{let o=M.outfit();o=M.wear(o,'dress-0');assert.equal(o.top,undefined);assert.equal(o.bottom,undefined);assert.ok(M.ready(o));o=M.wear(o,'top-0');assert.equal(o.dress,undefined);assert.equal(M.ready(o),false);o=M.wear(o,'bottom-0');assert.ok(M.ready(o));o=M.wear(o,'accessory-0');o=M.wear(o,'accessory-1');o=M.wear(o,'accessory-6');assert.equal(o.head,'accessory-1');assert.equal(o.neck,'accessory-6');});
test('scores are bounded, repeatable, and derived from choices',()=>{for(const t of D.themes){for(let n=0;n<70;n++){let o=M.wear(M.outfit(),D.items[n].id);const score=M.score(o,t);assert.deepEqual(score,M.score(o,t));assert.ok(score.total>=0&&score.total<=100);assert.equal(score.total,score.themeMatch+score.colorMatch+score.accessories+score.styleBonus);}}assert.notEqual(M.score(M.outfit(),D.themes[0]).total,M.score(M.outfit(),D.themes[11]).total);assert.equal(M.score({},D.themes[0]).total,0);});
test('every theme has multiple strong outfits, no single correct solution',()=>{for(const t of D.themes){let strong=new Set();const matches=i=>t.tags.some(tag=>i.tags.includes(tag));const base={};for(const slot of ['hair','head','neck','bag']){const candidates=D.items.filter(i=>i.slot===slot&&matches(i));candidates.sort((a,b)=>Number(t.colors.includes(b.color))-Number(t.colors.includes(a.color)));if(candidates.length)base[slot]=candidates[0].id;}
const uppers=D.items.filter(i=>['dress','top'].includes(i.category));for(const upper of uppers){const bottoms=upper.category==='dress'?[null]:D.items.filter(i=>i.category==='bottom');for(const bottom of bottoms)for(const shoe of D.items.filter(i=>i.category==='shoes')){let o=M.wear(M.wear(base,upper.id),shoe.id);if(bottom)o=M.wear(o,bottom.id);if(M.score(o,t).total>=85)strong.add(JSON.stringify(o));}}assert.ok(strong.size>=3,`${t.name}: ${strong.size} strong outfits`);}});
test('daily challenge is UTC deterministic and rotates',()=>{const a=new Date('2026-09-30T00:00:00Z'),b=new Date('2026-09-30T23:59:59Z'),c=new Date('2026-10-01T00:00:00Z');assert.equal(M.daily(a).id,M.daily(b).id);assert.notEqual(M.daily(a).id,M.daily(c).id);});
test('daily storage preserves best only today; blocked and corrupt storage work',()=>{let data={};const storage={getItem:k=>data[k],setItem:(k,v)=>data[k]=v};const date=new Date('2026-09-30');M.saveDaily(storage,80,date);M.saveDaily(storage,60,date);assert.equal(M.readDaily(storage,date).best,80);assert.equal(M.readDaily(storage,new Date('2026-10-01')),null);data['fashion:daily:v1']='broken';assert.equal(M.readDaily(storage,date),null);assert.doesNotThrow(()=>M.saveDaily({getItem(){throw Error();},setItem(){throw Error();}},95,date));});
test('static SEO and discovery links are present',()=>{const html=fs.readFileSync('dress-up-game/index.html','utf8');assert.equal((html.match(/<h1>/g)||[]).length,1);assert.ok(html.includes('https://puzzleten.com/dress-up-game/'));assert.ok(!html.includes('noindex'));assert.equal(JSON.parse(html.match(/application\/ld\+json">(.*?)<\/script>/)[1])['@type'],'WebPage');for(const heading of ['Play a Dress Up Game Online','How to Play','Fashion Challenge','Create Your Own Outfit','Dress Up Game FAQ'])assert.ok(html.includes(heading));assert.ok(fs.readFileSync('sitemap.xml','utf8').includes('https://puzzleten.com/dress-up-game/'));assert.ok(fs.readFileSync('index.html','utf8').includes('href="dress-up-game/"'));});
