const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),M=require('../memory-matching-game/model.js');
for(const t of Object.keys(M.themes))for(const d of Object.keys(M.levels))test(`${t}/${d}: 100 valid completable boards`,()=>{for(let n=0;n<100;n++){const g=new M.Game(t,d),groups=new Map();g.cards.forEach((c,i)=>groups.set(c.id,[...(groups.get(c.id)||[]),i]));assert.equal(groups.size,M.levels[d]);assert.equal(g.cards.length,M.levels[d]*2);for(const pair of groups.values()){assert.equal(pair.length,2);assert.deepEqual(g.cards[pair[0]],g.cards[pair[1]]);g.flip(pair[0]);g.flip(pair[1]);}assert.ok(g.complete);assert.equal(g.moves,g.pairs);}});
test('invalid, repeat and rapid third clicks cannot corrupt the round',()=>{const g=new M.Game();assert.equal(g.flip(-1),'ignored');g.flip(0);assert.equal(g.flip(0),'ignored');assert.equal(g.moves,0);const b=g.cards.findIndex(c=>c.id!==g.cards[0].id);assert.equal(g.flip(b),'miss');assert.equal(g.flip(2),'ignored');assert.equal(g.moves,1);g.conceal();g.flip(0);g.flip(g.cards.findIndex((c,i)=>i&&c.id===g.cards[0].id));assert.equal(g.flip(0),'ignored');});
test('best favors fewer moves then faster time',()=>{assert.ok(M.better({moves:7,seconds:99},{moves:8,seconds:10}));assert.ok(M.better({moves:8,seconds:9},{moves:8,seconds:10}));assert.equal(M.better({moves:9,seconds:1},{moves:8,seconds:10}),false);});
function harness(store=new Map(),blocked=false){let now=0,next=0;const jobs=new Map(),events=[],els=new Map(),listeners={};function el(){const classes=new Set();return {children:[],value:'',hidden:false,textContent:'',dataset:{},attrs:{},classList:{toggle(n,on){on?classes.add(n):classes.delete(n);},add(n){classes.add(n);},contains:n=>classes.has(n)},setAttribute(n,v){this.attrs[n]=v;},append(...n){this.children.push(...n);},replaceChildren(){this.children=[];},addEventListener(t,f){this[t]=f;},focus(){this.focused=true;}};}const get=id=>{if(!els.has(id))els.set(id,el());return els.get(id);};get('theme').value='animals';get('difficulty').value='easy';const doc={getElementById:get,createElement:el,hidden:false,addEventListener(t,f){listeners[t]=f;}};const context={document:doc,window:{addEventListener(){}},performance:{now:()=>now},MemoryModel:M,Prefs:{read(k,f){return blocked?f:store.get(k)??f;},write(k,v){if(!blocked)store.set(k,v);}},track:(name,p)=>events.push({name,...p}),setTimeout:f=>{jobs.set(++next,f);return next;},clearTimeout:id=>jobs.delete(id),setInterval:f=>{jobs.set(++next,f);return next;},clearInterval:id=>jobs.delete(id),getComputedStyle:()=>({gridTemplateColumns:'1fr 1fr 1fr 1fr'})};vm.runInNewContext(fs.readFileSync('memory-matching-game/game.js','utf8'),context);const cards=()=>get('board').children,identity=b=>b.children[1].children[1]?.textContent||b.children[1].textContent;return {get,cards,events,jobs,store,advance(ms){now+=ms;},visibility(hidden){doc.hidden=hidden;listeners.visibilitychange();},drain(){for(const f of [...jobs.values()])f();},solve(){const groups=new Map();cards().forEach(b=>groups.set(identity(b),[...(groups.get(identity(b))||[]),b]));for(const pair of groups.values()){pair[0].click();pair[1].click();}},miss(){const a=cards()[0],b=cards().find(x=>identity(x)!==identity(a));a.click();b.click();}};}
test('ready on load; start/progress/completion fire once; clock stops',()=>{const h=harness();assert.equal(h.events.length,0);assert.equal(h.cards().length,12);h.solve();for(const n of ['game_start','game_progress','game_over'])assert.equal(h.events.filter(e=>e.name===n).length,1);assert.equal(h.get('completion').hidden,false);assert.equal(h.get('moves').textContent,6);assert.equal(h.jobs.size,0);});
test('restart cancels pending mismatch and timer',()=>{const h=harness();h.miss();assert.equal(h.jobs.size,2);h.get('new-game').click();assert.equal(h.jobs.size,0);h.drain();assert.equal(h.get('moves').textContent,0);assert.ok(h.cards().every(c=>!c.classList.contains('revealed')));});
test('every theme/level switches safely during mismatch and completes',()=>{const h=harness();for(const t of Object.keys(M.themes))for(const d of Object.keys(M.levels)){h.get('new-game').click();h.miss();h.get('theme').value=t;h.get('difficulty').value=d;h.get('theme').change();assert.equal(h.jobs.size,0);assert.equal(h.cards().length,2*M.levels[d]);h.solve();assert.equal(h.get('completion').hidden,false);}});
test('timer starts at first card and excludes hidden time',()=>{const h=harness();h.advance(2000);h.cards()[0].click();h.advance(3000);h.visibility(true);h.advance(9000);h.visibility(false);h.advance(2000);h.drain();assert.equal(h.get('time').textContent,'0:05');});
test('reload keeps best but resets board; levels use separate bests',()=>{const h=harness();h.solve();const r=harness(h.store);assert.match(r.get('best').textContent,/6 moves/);assert.equal(r.get('moves').textContent,0);r.get('difficulty').value='hard';r.get('difficulty').change();assert.equal(r.get('best').textContent,'Set your first best');});
test('blocked or malformed storage does not break play',()=>{const h=harness(new Map(),true);h.solve();assert.equal(h.get('completion').hidden,false);const bad=harness(new Map([['memory-best-v1:animals:easy',{moves:-1,seconds:'bad'}]]));assert.equal(bad.get('best').textContent,'Set your first best');bad.solve();});
test('arrow navigation; hidden identities inaccessible to screen readers',()=>{const h=harness();h.cards()[0].keydown({key:'ArrowRight',preventDefault(){}});assert.ok(h.cards()[1].focused);assert.equal(h.cards()[0].attrs['aria-label'],'Card 1: face down');assert.equal(h.cards()[0].children[1].attrs['aria-hidden'],'true');});
test('SEO source and assets',()=>{const html=fs.readFileSync('memory-matching-game/index.html','utf8');assert.equal((html.match(/<h1>/g)||[]).length,1);assert.match(html,/<h1>Memory Matching Game<\/h1>/);assert.equal((html.match(/rel="canonical"/g)||[]).length,1);assert.match(html,/href="https:\/\/puzzleten.com\/memory-matching-game\/"/);assert.doesNotMatch(html,/noindex/);assert.match(html,/<h2>Memory Game Themes/);assert.match(fs.readFileSync('sitemap.xml','utf8'),/<loc>https:\/\/puzzleten.com\/memory-matching-game\/<\/loc>/);for(const t of Object.keys(M.themes).filter(t=>t!=='letters'))for(let i=0;i<12;i++)assert.ok(fs.existsSync(`memory-matching-game/art/${t}-${i}.svg`));});
