(async()=>{
  const root=document.getElementById('fixture');let game,passed=0,failed=0;const errors=[];window.addEventListener('error',e=>errors.push(e.message));const assert=(v,m='Assertion failed')=>{if(!v)throw Error(m);};
  const memory=()=>{const d={};return {getItem:k=>d[k]??null,setItem:(k,v)=>d[k]=v};};
  function fresh(storage=memory()){game?.destroy();game=new ShapeSliceGame(root,{storage});return game;}
  async function test(name,fn){const li=document.createElement('li');try{await fn();li.textContent='PASS: '+name;passed++;}catch(e){li.textContent='FAIL: '+name+' — '+e.message;failed++;}document.getElementById('checks').append(li);}
  function pointer(g,type,p,kind='touch'){const r=g.board.getBoundingClientRect();g.board.dispatchEvent(new PointerEvent(type,{bubbles:true,pointerId:4,pointerType:kind,isPrimary:true,button:0,clientX:r.left+p[0]*r.width/400,clientY:r.top+p[1]*r.height/340}));}
  await test('touch drag solves opening round, creates real pieces and unlocks Next',()=>{const g=fresh();g.board.setPointerCapture=()=>{};pointer(g,'pointerdown',[100,70]);pointer(g,'pointermove',[300,270]);assert(g.$('line').getAttribute('visibility')==='visible');pointer(g,'pointerup',[300,270]);assert(g.result.pass);assert(g.$('shapes').querySelectorAll('.ss-piece').length===2);assert(!g.$('next').hidden);assert(g.session.score===200);assert(getComputedStyle(g.board).touchAction==='none');});
  await test('two-tap alternative and cancellation do not accidentally score',()=>{const g=fresh();g.board.setPointerCapture=()=>{};pointer(g,'pointerdown',[100,70]);pointer(g,'pointerup',[100,70]);assert(!!g.tapStart);g.board.dispatchEvent(new PointerEvent('pointercancel',{bubbles:true}));assert(!g.tapStart);assert(g.session.score===0);for(const p of [[100,70],[300,270]]){pointer(g,'pointerdown',p);pointer(g,'pointerup',p);}assert(g.result.pass);});
  await test('failed cut explains why, retry is immediate and does not advance',()=>{const g=fresh();g.submit([60,170],[340,170]);assert(!g.result.pass);assert(g.$('detail').textContent.includes('4- and 4-sided'));assert(g.$('next').hidden);g.$('retry').click();assert(!g.result);assert(g.at===0);assert(g.session.score===0);assert(document.activeElement===g.board);g.submit(...g.puzzle.solution);assert(g.result.pass);});
  await test('same successful retry does not farm score or streak',()=>{const g=fresh();g.submit(...g.puzzle.solution);const score=g.session.score,streak=g.session.streak;g.$('retry').click();g.submit(...g.puzzle.solution);assert(g.session.score===score);assert(g.session.streak===streak);});
  await test('all 32 rendered configurations are solvable; finish and Play Again work',()=>{const g=fresh();for(let i=0;i<32;i++){assert(g.at===i);g.submit(...g.puzzle.solution);assert(g.result.pass,'level '+(i+1));assert(g.$('shapes').querySelectorAll('polygon').length>=2);g.$('next').click();}assert(g.complete);assert(!g.$('complete').hidden);assert(g.$('summary').textContent.includes('32 challenges'));const best=g.best;g.$('again').click();assert(!g.complete);assert(g.at===0);assert(!g.result);assert(g.session.score===0);assert(g.best===best);g.submit(...g.puzzle.solution);assert(g.result.pass);});
  await test('best score and best streak restore; blocked and corrupted storage are safe',()=>{const storage=memory();let g=fresh(storage);g.submit(...g.puzzle.solution);g.next();g.submit(...g.puzzle.solution);const score=g.best,streak=g.bestStreak;g=fresh(storage);assert(g.best===score);assert(g.bestStreak===streak);assert(g.session.score===0);for(const storage of [{getItem:()=>'{',setItem:()=>{}},{getItem:()=>{throw Error('blocked');},setItem:()=>{throw Error('blocked');}}]){g=fresh(storage);g.submit(...g.puzzle.solution);assert(g.result.pass);}});
  await test('keyboard endpoints can solve, and Escape cancels',()=>{const g=fresh();const key=key=>g.board.dispatchEvent(new KeyboardEvent('keydown',{key,bubbles:true,cancelable:true}));for(let i=0;i<10;i++){key('ArrowLeft');key('ArrowUp');}key('Enter');assert(g.tapStart[0]===100&&g.tapStart[1]===70);key('Escape');assert(!g.tapStart);key('Enter');for(let i=0;i<20;i++){key('ArrowRight');key('ArrowDown');}key('Enter');assert(g.result.pass);});
  await test('area percentages and accuracy appear in the rendered result',()=>{const g=fresh();g.at=4;g.load();g.submit([155,20],[155,310]);assert(g.result.pass);assert(g.$('detail').textContent.includes('90%'));assert(g.$('shapes').textContent.includes('27.5%'));});
  await test('hint is optional, lightweight and does not award points',()=>{const g=fresh();g.at=15;g.load();g.$('hintButton').click();assert(g.$('hint').querySelector('line'));assert(g.session.score===0);assert(g.$('detail').textContent.length>0);});
  await test('small container has no overflow and controls remain touch-sized',()=>{const g=fresh();root.style.width='280px';g.submit(...g.puzzle.solution);assert(root.scrollWidth<=root.clientWidth+1);assert(g.$('next').getBoundingClientRect().height>=44);assert(g.$('retry').getBoundingClientRect().height>=44);root.style.width='';});
  await test('opening demo never scores, cancels on input and does not replay',()=>{const g=fresh();assert(g.session.score===0);if(!window.matchMedia('(prefers-reduced-motion: reduce)').matches){assert(g.demoActive);assert(g.$('hint').querySelector('.ss-demo-pointer'));g.board.setPointerCapture=()=>{};pointer(g,'pointerdown',[100,70]);assert(!g.demoActive);assert(!g.$('shapes').classList.contains('ss-demo-original'));pointer(g,'pointerup',[100,70]);assert(g.session.score===0);g.retry();assert(!g.demoActive);assert(!g.$('hint').querySelector('.ss-demo-pointer'));}});
  await test('no uncaught browser errors',()=>assert(!errors.length,errors.join('; ')));
  fresh();document.getElementById('results').textContent=`${passed} passed, ${failed} failed`;document.title=`Shape Slice: ${passed} passed, ${failed} failed`;
})();
