/*
 * Word lists, one entry per theme.
 *
 * `learner` words are short and common, and each carries a plain one-line
 * meaning written for someone whose English is limited — the meaning is shown
 * when the word is found, which is the only teaching the mode does.
 *
 * `native` words are longer and deliberately less obvious. No meanings; the
 * challenge there is finding them, not understanding them.
 *
 * Nothing here may be longer than the smallest grid it can appear in (10 for
 * learner, 13 for native), or it can never be placed.
 */
const THEMES = [
  {
    key: 'animals',
    name: 'Animals',
    learner: [
      { word: 'CAT',   meaning: 'a small pet with whiskers' },
      { word: 'DOG',   meaning: 'a pet that barks' },
      { word: 'COW',   meaning: 'a farm animal that gives milk' },
      { word: 'PIG',   meaning: 'a pink farm animal' },
      { word: 'HEN',   meaning: 'a female chicken' },
      { word: 'FISH',  meaning: 'an animal that lives in water' },
      { word: 'BIRD',  meaning: 'an animal with wings' },
      { word: 'DUCK',  meaning: 'a bird that swims' },
      { word: 'GOAT',  meaning: 'a farm animal with horns' },
      { word: 'HORSE', meaning: 'a large animal you can ride' },
      { word: 'SHEEP', meaning: 'a farm animal with wool' },
      { word: 'MOUSE', meaning: 'a very small animal with a long tail' },
    ],
    native: [
      'ELEPHANT', 'PORCUPINE', 'ALBATROSS', 'CHIMPANZEE', 'RHINOCEROS',
      'HEDGEHOG', 'FLAMINGO', 'CROCODILE', 'PANGOLIN', 'WOLVERINE',
      'ARMADILLO', 'MONGOOSE', 'OTTER', 'BADGER', 'HERON', 'LEMUR',
      'TAPIR', 'IGUANA',
    ],
  },

  {
    key: 'food',
    name: 'Food',
    learner: [
      { word: 'EGG',    meaning: 'a food that comes from a hen' },
      { word: 'RICE',   meaning: 'small white grains you boil' },
      { word: 'MILK',   meaning: 'a white drink from a cow' },
      { word: 'SOUP',   meaning: 'a hot liquid food you eat with a spoon' },
      { word: 'CAKE',   meaning: 'a sweet food for birthdays' },
      { word: 'MEAT',   meaning: 'food that comes from an animal' },
      { word: 'SALT',   meaning: 'white grains that make food taste better' },
      { word: 'BREAD',  meaning: 'a food made from flour, baked in an oven' },
      { word: 'APPLE',  meaning: 'a round red or green fruit' },
      { word: 'JUICE',  meaning: 'a drink made from fruit' },
      { word: 'HONEY',  meaning: 'a sweet food made by bees' },
      { word: 'CHEESE', meaning: 'a solid food made from milk' },
    ],
    native: [
      'ASPARAGUS', 'ARTICHOKE', 'CINNAMON', 'MERINGUE', 'RISOTTO',
      'AUBERGINE', 'CORIANDER', 'PARMESAN', 'ANCHOVY', 'MARZIPAN',
      'RHUBARB', 'SAFFRON', 'CHUTNEY', 'GNOCCHI', 'PISTACHIO',
      'TAMARIND', 'POLENTA', 'QUINCE',
    ],
  },

  {
    key: 'colours',
    name: 'Colors',
    learner: [
      { word: 'RED',    meaning: 'the color of blood' },
      { word: 'BLUE',   meaning: 'the color of the sky' },
      { word: 'PINK',   meaning: 'a light red color' },
      { word: 'GREY',   meaning: 'the color between black and white' },
      { word: 'GOLD',   meaning: 'the color of a shiny yellow metal' },
      { word: 'GREEN',  meaning: 'the color of grass' },
      { word: 'BLACK',  meaning: 'the color of night' },
      { word: 'WHITE',  meaning: 'the color of snow' },
      { word: 'BROWN',  meaning: 'the color of wood or soil' },
      { word: 'ORANGE', meaning: 'the color between red and yellow' },
      { word: 'PURPLE', meaning: 'the color between red and blue' },
      { word: 'SILVER', meaning: 'the color of a shiny grey metal' },
    ],
    native: [
      'VERMILION', 'TURQUOISE', 'CHARTREUSE', 'BURGUNDY', 'LAVENDER',
      'MAGENTA', 'CERULEAN', 'SCARLET', 'EMERALD', 'CRIMSON',
      'INDIGO', 'MAROON', 'VIOLET', 'AMBER', 'OCHRE', 'TEAL',
      'SEPIA', 'MAUVE',
    ],
  },

  {
    key: 'halloween',
    name: 'Halloween',
    learner: [
      { word: 'BAT',     meaning: 'a small animal that flies at night' },
      { word: 'CAT',      meaning: 'a small pet that says meow' },
      { word: 'MASK',     meaning: 'you wear this to cover your face' },
      { word: 'MOON',     meaning: 'it shines in the sky at night' },
      { word: 'DARK',     meaning: 'when there is no light at all' },
      { word: 'CANDY',    meaning: 'sweet treats children collect' },
      { word: 'GHOST',    meaning: 'the spirit of a dead person, in stories' },
      { word: 'WITCH',    meaning: 'a woman in stories who does magic' },
      { word: 'BONES',    meaning: 'the hard white parts inside a body' },
      { word: 'BROOM',    meaning: 'you sweep the floor with this' },
      { word: 'SPIDER',   meaning: 'a small creature with eight legs' },
      { word: 'PUMPKIN',  meaning: 'a big orange vegetable people carve' },
    ],
    native: [
      'SKELETON', 'VAMPIRE', 'WEREWOLF', 'HAUNTED', 'CAULDRON', 'GRAVEYARD',
      'COSTUME', 'LANTERN', 'GOBLIN', 'ZOMBIE', 'POTION', 'COBWEB',
      'SHADOW', 'MIDNIGHT', 'PHANTOM', 'SPECTRE', 'TOMBSTONE', 'MUMMY',
    ],
  },

  {
    key: 'christmas',
    name: 'Christmas',
    learner: [
      { word: 'ELF',      meaning: 'a small helper in a red and green hat' },
      { word: 'TREE',     meaning: 'a tall plant people decorate in December' },
      { word: 'GIFT',     meaning: 'something you wrap and give to someone' },
      { word: 'SNOW',     meaning: 'soft white flakes falling from the sky' },
      { word: 'STAR',     meaning: 'it shines at night, and tops the tree' },
      { word: 'BELL',     meaning: 'a metal cup that rings when you shake it' },
      { word: 'SANTA',    meaning: 'the man in red who brings presents' },
      { word: 'CAROL',    meaning: 'a song people sing in December' },
      { word: 'ANGEL',    meaning: 'a figure with wings, usually in white' },
      { word: 'SLEIGH',   meaning: 'a sledge pulled across the snow' },
      { word: 'CANDLE',   meaning: 'wax with a wick that gives light' },
      { word: 'REINDEER', meaning: 'an animal with antlers that pulls a sledge' },
    ],
    native: [
      'MISTLETOE', 'TINSEL', 'NATIVITY', 'WREATH', 'GARLAND', 'CHIMNEY',
      'STOCKING', 'ORNAMENT', 'MARZIPAN', 'PANTOMIME', 'YULETIDE', 'CRACKER',
      'BAUBLE', 'EPIPHANY', 'MANGER', 'TOBOGGAN', 'SPRUCE', 'FRANKINCENSE',
    ],
  },

  {
    key: 'space',
    name: 'Space',
    learner: [
      { word: 'SKY',    meaning: 'what you see above you outdoors' },
      { word: 'SUN',    meaning: 'the star that gives us light and heat' },
      { word: 'MOON',   meaning: 'it circles the Earth and glows at night' },
      { word: 'STAR',   meaning: 'a burning ball of gas, very far away' },
      { word: 'MARS',   meaning: 'the red planet, fourth from the sun' },
      { word: 'EARTH',  meaning: 'the planet we live on' },
      { word: 'ORBIT',  meaning: 'the path one body takes around another' },
      { word: 'COMET',  meaning: 'an icy body with a long bright tail' },
      { word: 'ALIEN',  meaning: 'a living thing from another world' },
      { word: 'LUNAR',  meaning: 'to do with the moon' },
      { word: 'ROCKET', meaning: 'it launches into the sky on a column of fire' },
      { word: 'PLANET', meaning: 'a large body that circles a star' },
    ],
    native: [
      'ASTEROID', 'NEBULA', 'GALAXY', 'SATELLITE', 'ECLIPSE', 'METEORITE',
      'TELESCOPE', 'GRAVITY', 'SUPERNOVA', 'ASTRONAUT', 'JUPITER', 'SATURN',
      'NEPTUNE', 'URANUS', 'MERCURY', 'PULSAR', 'QUASAR', 'COSMOS',
    ],
  },

  {
    key: 'ocean',
    name: 'Ocean',
    learner: [
      { word: 'FISH',  meaning: 'an animal that swims and has gills' },
      { word: 'CRAB',  meaning: 'it walks sideways and has claws' },
      { word: 'WAVE',  meaning: 'moving water that rolls onto a beach' },
      { word: 'SAND',  meaning: 'tiny grains you walk on at the beach' },
      { word: 'BOAT',  meaning: 'it floats and carries people on water' },
      { word: 'SEAL',  meaning: 'a smooth grey animal that barks' },
      { word: 'DEEP',  meaning: 'a very long way down' },
      { word: 'SHARK', meaning: 'a large fish with rows of sharp teeth' },
      { word: 'WHALE', meaning: 'the biggest animal in the sea' },
      { word: 'SHELL', meaning: 'the hard case a sea creature leaves behind' },
      { word: 'CORAL', meaning: 'a hard, colourful growth under the sea' },
      { word: 'SQUID', meaning: 'a soft creature with ten arms' },
    ],
    native: [
      'PLANKTON', 'BARNACLE', 'ANEMONE', 'JELLYFISH', 'SEAHORSE', 'STINGRAY',
      'OCTOPUS', 'DOLPHIN', 'LOBSTER', 'TRENCH', 'CURRENT', 'LAGOON',
      'ESTUARY', 'MOLLUSC', 'CRUSTACEAN', 'NAUTILUS', 'ABYSS', 'KELP',
    ],
  },

  {
    key: 'dinosaurs',
    name: 'Dinosaurs',
    learner: [
      { word: 'EGG',    meaning: 'a shell with a baby animal growing inside' },
      { word: 'BONE',   meaning: 'a hard white part of a skeleton' },
      { word: 'CLAW',   meaning: 'a sharp curved nail on a foot' },
      { word: 'TAIL',   meaning: 'the long part at the back of an animal' },
      { word: 'HORN',   meaning: 'a hard point growing from the head' },
      { word: 'ROAR',   meaning: 'a very loud, very deep sound' },
      { word: 'NEST',   meaning: 'where eggs are kept safe' },
      { word: 'TOOTH',  meaning: 'used for biting and chewing' },
      { word: 'SCALE',  meaning: 'one of the small plates covering skin' },
      { word: 'GIANT',  meaning: 'extremely large' },
      { word: 'SPIKE',  meaning: 'a sharp pointed part sticking out' },
      { word: 'FOSSIL', meaning: 'remains that have slowly turned to stone' },
    ],
    native: [
      'TRICERATOPS', 'STEGOSAURUS', 'PTERODACTYL', 'SPINOSAURUS', 'ALLOSAURUS',
      'DIPLODOCUS', 'IGUANODON', 'CRETACEOUS', 'MESOZOIC', 'JURASSIC',
      'TRIASSIC', 'PREDATOR', 'CARNIVORE', 'HERBIVORE', 'SKELETON',
      'EXTINCT', 'AMBER', 'TALON',
    ],
  },

  {
    key: 'sports',
    name: 'Sports',
    learner: [
      { word: 'RUN',   meaning: 'move fast on your feet' },
      { word: 'WIN',   meaning: 'finish first, or beat the other side' },
      { word: 'BALL',  meaning: 'a round thing you kick or throw' },
      { word: 'SWIM',  meaning: 'move yourself through water' },
      { word: 'JUMP',  meaning: 'push off the ground into the air' },
      { word: 'TEAM',  meaning: 'a group who play on the same side' },
      { word: 'GOAL',  meaning: 'where you score a point' },
      { word: 'RACE',  meaning: 'a contest to be the fastest' },
      { word: 'KICK',  meaning: 'hit something with your foot' },
      { word: 'THROW', meaning: 'send something through the air by hand' },
      { word: 'CATCH', meaning: 'take hold of something in the air' },
      { word: 'MATCH', meaning: 'a game between two sides' },
    ],
    native: [
      'BADMINTON', 'GYMNASTICS', 'ATHLETICS', 'LACROSSE', 'ROUNDERS',
      'ARCHERY', 'FENCING', 'CANOEING', 'TRIATHLON', 'DECATHLON',
      'SNOOKER', 'CURLING', 'HANDBALL', 'ROWING', 'SAILING', 'SKATING',
      'HURDLES', 'DISCUS',
    ],
  },

  {
    key: 'body',
    name: 'The Body',
    learner: [
      { word: 'ARM',    meaning: 'the long part between shoulder and hand' },
      { word: 'LEG',    meaning: 'you walk on two of these' },
      { word: 'HAND',   meaning: 'you hold things with this' },
      { word: 'FOOT',   meaning: 'you stand on two of these' },
      { word: 'HEAD',   meaning: 'the top of your body, above the neck' },
      { word: 'NOSE',   meaning: 'you smell and breathe through this' },
      { word: 'HAIR',   meaning: 'it grows on top of your head' },
      { word: 'KNEE',   meaning: 'the joint in the middle of your leg' },
      { word: 'MOUTH',  meaning: 'you eat and speak with this' },
      { word: 'TOOTH',  meaning: 'you chew your food with these' },
      { word: 'HEART',  meaning: 'it beats inside your chest' },
      { word: 'FINGER', meaning: 'you have five of these on each hand' },
    ],
    native: [
      'SHOULDER', 'ELBOW', 'ANKLE', 'WRIST', 'KNUCKLE', 'EYEBROW',
      'EYELASH', 'FOREHEAD', 'THUMB', 'SPINE', 'RIBCAGE', 'COLLARBONE',
      'TENDON', 'KIDNEY', 'PANCREAS', 'ABDOMEN', 'TEMPLE', 'LIVER',
    ],
  },

  {
    key: 'thanksgiving',
    name: 'Thanksgiving',
    learner: [
      { word: 'CORN',    meaning: 'a yellow vegetable that grows on a cob' },
      { word: 'PIE',     meaning: 'a sweet dish baked inside pastry' },
      { word: 'FEAST',   meaning: 'a big meal shared by a lot of people' },
      { word: 'TABLE',   meaning: 'you sit around this to eat' },
      { word: 'GRAVY',   meaning: 'a warm brown sauce poured over meat' },
      { word: 'BREAD',   meaning: 'a food baked from flour and water' },
      { word: 'APPLE',   meaning: 'a round red or green fruit' },
      { word: 'THANKS',  meaning: 'what you say when someone helps you' },
      { word: 'FAMILY',  meaning: 'the people you are related to' },
      { word: 'TURKEY',  meaning: 'the big bird eaten on this day' },
      { word: 'LEAVES',  meaning: 'the flat parts of a tree that fall in autumn' },
      { word: 'HARVEST', meaning: 'the crops gathered in at the end of summer' },
    ],
    native: [
      'CRANBERRY', 'STUFFING', 'CASSEROLE', 'PILGRIM', 'GRATITUDE', 'CORNUCOPIA',
      'MAYFLOWER', 'DRUMSTICK', 'NOVEMBER', 'PUMPKIN', 'LEFTOVERS', 'TRADITION',
      'ABUNDANCE', 'WISHBONE', 'SQUASH', 'CIDER', 'PECAN', 'PARADE',
    ],
  },

  {
    key: 'winter',
    name: 'Winter',
    learner: [
      { word: 'SNOW',   meaning: 'soft white flakes that fall when it is cold' },
      { word: 'ICE',    meaning: 'water that has frozen hard' },
      { word: 'COLD',   meaning: 'the opposite of hot' },
      { word: 'COAT',   meaning: 'a warm thing you wear outdoors' },
      { word: 'HAT',    meaning: 'you wear this on your head' },
      { word: 'FIRE',   meaning: 'it burns and gives off heat' },
      { word: 'SLED',   meaning: 'you sit on this to slide down snow' },
      { word: 'WARM',   meaning: 'a little bit hot, in a nice way' },
      { word: 'SCARF',  meaning: 'you wrap this around your neck' },
      { word: 'FROST',  meaning: 'thin white ice on grass and windows' },
      { word: 'BOOTS',  meaning: 'strong shoes that cover your ankles' },
      { word: 'GLOVES', meaning: 'you wear these on your hands' },
    ],
    native: [
      'BLIZZARD', 'ICICLE', 'SNOWFLAKE', 'HIBERNATE', 'TOBOGGAN', 'MITTENS',
      'FIREPLACE', 'FROSTBITE', 'AVALANCHE', 'SNOWDRIFT', 'SOLSTICE', 'MIDWINTER',
      'GLACIER', 'THERMAL', 'CHIMNEY', 'FLURRY', 'SHIVER', 'WOOLEN',
    ],
  },

  {
    key: 'newyear',
    name: 'New Year',
    learner: [
      { word: 'YEAR',   meaning: 'twelve months, from January to December' },
      { word: 'WISH',   meaning: 'something you hope will happen' },
      { word: 'CAKE',   meaning: 'a sweet food baked for special days' },
      { word: 'PARTY',  meaning: 'a happy gathering with food and music' },
      { word: 'CLOCK',  meaning: 'it shows you what time it is' },
      { word: 'HAPPY',  meaning: 'the feeling of being pleased' },
      { word: 'DANCE',  meaning: 'to move your body in time to music' },
      { word: 'MUSIC',  meaning: 'sounds made by singing or instruments' },
      { word: 'NIGHT',  meaning: 'the dark hours when most people sleep' },
      { word: 'FRIEND', meaning: 'someone you like and spend time with' },
      { word: 'TWELVE', meaning: 'the number that comes after eleven' },
      { word: 'LIGHTS', meaning: 'lamps that shine in the dark' },
    ],
    native: [
      'RESOLUTION', 'MIDNIGHT', 'CELEBRATE', 'FIREWORKS', 'CONFETTI', 'COUNTDOWN',
      'CHAMPAGNE', 'STREAMER', 'TRADITION', 'CALENDAR', 'SPARKLER', 'JUBILANT',
      'JANUARY', 'FESTIVE', 'GLITTER', 'BALLOON', 'REVELRY', 'TOAST',
    ],
  },

  {
    key: 'valentines',
    name: 'Valentine\'s Day',
    learner: [
      { word: 'LOVE',   meaning: 'a strong warm feeling for someone' },
      { word: 'HUG',    meaning: 'to hold someone in your arms' },
      { word: 'GIFT',   meaning: 'something you give to someone' },
      { word: 'CARD',   meaning: 'folded paper with a message inside' },
      { word: 'KISS',   meaning: 'to touch someone with your lips' },
      { word: 'ROSE',   meaning: 'a flower with a sweet smell and thorns' },
      { word: 'PINK',   meaning: 'a light red color' },
      { word: 'HEART',  meaning: 'the shape people use to mean love' },
      { word: 'SWEET',  meaning: 'tasting of sugar' },
      { word: 'CANDY',  meaning: 'sweet treats made of sugar' },
      { word: 'FRIEND', meaning: 'someone you like and spend time with' },
      { word: 'FLOWER', meaning: 'the colorful part of a plant' },
    ],
    native: [
      'VALENTINE', 'AFFECTION', 'CHOCOLATE', 'SWEETHEART', 'ADORATION', 'COURTSHIP',
      'ROMANTIC', 'DEVOTION', 'ENAMORED', 'FEBRUARY', 'SERENADE', 'BOUQUET',
      'CHERISH', 'ADMIRER', 'BELOVED', 'PASSION', 'CUPID', 'TOKEN',
    ],
  },

  {
    key: 'easter',
    name: 'Easter',
    learner: [
      { word: 'EGG',    meaning: 'a round thing a bird lays' },
      { word: 'LAMB',   meaning: 'a baby sheep' },
      { word: 'NEST',   meaning: 'the home a bird builds for its eggs' },
      { word: 'HUNT',   meaning: 'to search hard for something hidden' },
      { word: 'HIDE',   meaning: 'to put something where it cannot be seen' },
      { word: 'BUNNY',  meaning: 'another word for a rabbit' },
      { word: 'CHICK',  meaning: 'a baby chicken' },
      { word: 'GRASS',  meaning: 'the green plants that cover a lawn' },
      { word: 'PAINT',  meaning: 'colored liquid you brush onto things' },
      { word: 'CANDY',  meaning: 'sweet treats made of sugar' },
      { word: 'BASKET', meaning: 'a container with a handle for carrying things' },
      { word: 'SPRING', meaning: 'the season that follows winter' },
    ],
    native: [
      'MARSHMALLOW', 'SPRINGTIME', 'CHOCOLATE', 'CELEBRATE', 'DAFFODIL', 'DUCKLING',
      'HYACINTH', 'DECORATE', 'EGGSHELL', 'BLOSSOM', 'SUNRISE', 'RENEWAL',
      'CROCUS', 'BONNET', 'PARADE', 'RIBBON', 'PASTEL', 'TULIP',
    ],
  },

  {
    key: 'stpatricks',
    name: 'St. Patrick\'s Day',
    learner: [
      { word: 'POT',    meaning: 'a deep round container' },
      { word: 'HAT',    meaning: 'you wear this on your head' },
      { word: 'LUCK',   meaning: 'good things happening by chance' },
      { word: 'GOLD',   meaning: 'a shiny yellow metal worth a lot' },
      { word: 'SONG',   meaning: 'words sung to music' },
      { word: 'FLAG',   meaning: 'a piece of cloth that stands for a country' },
      { word: 'GREEN',  meaning: 'the color of grass' },
      { word: 'IRISH',  meaning: 'from the country of Ireland' },
      { word: 'DANCE',  meaning: 'to move your body in time to music' },
      { word: 'RIVER',  meaning: 'water flowing across the land' },
      { word: 'CLOVER', meaning: 'a small plant with three round leaves' },
      { word: 'PARADE', meaning: 'people marching through the streets' },
    ],
    native: [
      'LEPRECHAUN', 'SHILLELAGH', 'CLOVERLEAF', 'SHAMROCK', 'FOLKLORE', 'TRADITION',
      'HERITAGE', 'LIMERICK', 'FESTIVAL', 'IRELAND', 'EMERALD', 'BLARNEY',
      'RAINBOW', 'DUBLIN', 'CELTIC', 'FIDDLE', 'PATRON', 'MARCH',
    ],
  },

  {
    key: 'spring',
    name: 'Spring',
    learner: [
      { word: 'SUN',    meaning: 'the bright star that lights the day' },
      { word: 'BUD',    meaning: 'a flower before it opens' },
      { word: 'RAIN',   meaning: 'water falling from the clouds' },
      { word: 'SEED',   meaning: 'a small thing a new plant grows from' },
      { word: 'GROW',   meaning: 'to get bigger over time' },
      { word: 'BIRD',   meaning: 'an animal with feathers that can fly' },
      { word: 'NEST',   meaning: 'the home a bird builds for its eggs' },
      { word: 'LEAF',   meaning: 'a flat green part of a plant' },
      { word: 'WARM',   meaning: 'a little bit hot, in a nice way' },
      { word: 'GREEN',  meaning: 'the color of grass' },
      { word: 'FLOWER', meaning: 'the colorful part of a plant' },
      { word: 'GARDEN', meaning: 'a piece of ground where plants are grown' },
    ],
    native: [
      'GERMINATE', 'GREENHOUSE', 'PERENNIAL', 'MIGRATION', 'BUTTERFLY', 'BLUEBELL',
      'PRIMROSE', 'SEEDLING', 'FRAGRANT', 'DRIZZLE', 'EQUINOX', 'SHOWERS',
      'TADPOLE', 'SPROUT', 'MEADOW', 'POLLEN', 'NECTAR', 'BLOOM',
    ],
  },
];
