/* SVG presentation. All evaluation is delegated to the geometry model. */
class ShapeSliceGame {
  constructor(root,options={}){
    this.root=root;this.G=SliceGeometry;this.M=SliceModel;this.puzzles=SlicePuzzles.all;this.analytics=options.analytics||(()=>{});this.sound=options.sound;this.at=0;this.session=this.M.create();this.best=0;this.bestStreak=0;this.cursor=[200,170];this.timers=[];
    try{this.storage=options.storage||localStorage;const saved=JSON.parse(this.storage.getItem('shape-slice:v1'));if(saved){if(Number.isSafeInteger(saved.best)&&saved.best>=0)this.best=saved.best;if(Number.isSafeInteger(saved.bestStreak)&&saved.bestStreak>=0)this.bestStreak=saved.bestStreak;}}catch{}
    root.innerHTML=`<div class="ss-stats"><div>Score<strong data-ss="score">0</strong></div><div>Best<strong data-ss="best">0</strong></div><div>Streak<strong data-ss="streak">—</strong></div><div>Best streak<strong data-ss="bestStreak">—</strong></div></div>
    <div class="ss-round"><span data-ss="round"></span><button data-ss="sound" class="ss-small"></button></div>
    <h2 class="ss-objective" data-ss="objective"></h2><p class="ss-instruction" data-ss="instruction">Draw one straight line across the shape.</p>
    <div class="ss-stage"><svg data-ss="board" viewBox="0 0 400 340" role="application" aria-label="Slice board. Drag a line or tap two points. Keyboard: arrows move the cursor, Enter sets each endpoint, Escape cancels." tabindex="0"><defs><pattern id="ss-dots" width="20" height="20" patternUnits="userSpaceOnUse"><circle cx="10" cy="10" r="1" fill="#d8ddec"/></pattern><linearGradient id="ss-fill" x2="1" y2="1"><stop stop-color="#b9a1ee"/><stop offset="1" stop-color="#8771d4"/></linearGradient></defs><rect width="400" height="340" fill="url(#ss-dots)"/><g data-ss="shapes"></g><g data-ss="zones"></g><g data-ss="targets"></g><g data-ss="hint"></g><line data-ss="line" class="ss-cut" visibility="hidden"/><circle data-ss="cursor" class="ss-cursor" r="6" cx="200" cy="170" visibility="hidden"/></svg><span class="ss-score-pop" data-ss="pop" aria-hidden="true"></span></div>
    <div class="ss-feedback" data-ss="feedback" role="status" aria-live="polite" aria-atomic="true"><strong data-ss="verdict">One line. A fresh perspective.</strong><span data-ss="detail">Drag to slice, or tap a start and end point.</span></div>
    <div class="ss-controls"><button data-ss="retry" hidden>Try Again</button><button data-ss="hintButton">Hint</button><button class="ss-primary" data-ss="next" hidden>Next challenge →</button></div>
    <p class="ss-replay-note" data-ss="note">No timer. No lives. Find your line.</p>
    <section data-ss="complete" class="ss-complete" hidden><h2 tabindex="-1">A cut above!</h2><p data-ss="summary"></p><button data-ss="again" class="ss-primary">Play Again</button><a href="../#games">More PuzzleTen games →</a></section>`;
    this.board=this.$('board');this.board.addEventListener('pointerdown',e=>this.down(e));this.board.addEventListener('pointermove',e=>this.move(e));this.board.addEventListener('pointerup',e=>this.up(e));this.board.addEventListener('pointercancel',()=>this.cancel());this.board.addEventListener('lostpointercapture',()=>{if(this.pointer)this.cancel();});this.board.addEventListener('keydown',e=>this.key(e));
    this.$('retry').onclick=()=>this.retry();this.$('next').onclick=()=>this.next();this.$('hintButton').onclick=()=>this.hint();this.$('again').onclick=()=>{this.session=this.M.create();this.at=0;this.complete=false;this.started=false;this.$('complete').hidden=true;this.load();this.board.focus({preventScroll:true});};
    this.$('sound').onclick=()=>{this.sound?.setMuted(!this.sound.isMuted());this.renderSound();};this.load();this.renderSound();this.emit('game_view');
  }
  $(key){return this.root.querySelector('[data-ss="'+key+'"]');}
  emit(name,data={}){try{this.analytics(name,{game_name:'shape_slice',...data});}catch{}}
  save(){try{this.storage.setItem('shape-slice:v1',JSON.stringify({best:this.best,bestStreak:this.bestStreak}));}catch{}}
  renderSound(){this.$('sound').hidden=!this.sound;this.$('sound').textContent=this.sound?.isMuted()?'Sound off':'Sound on';this.$('sound').setAttribute('aria-pressed',String(!!this.sound&&!this.sound.isMuted()));}
  stats(){for(const k of ['score','streak'])this.$(k).textContent=k==='streak'?(this.session.streak?'×'+this.session.streak:'—'):this.session.score.toLocaleString();this.$('best').textContent=this.best.toLocaleString();this.$('bestStreak').textContent=this.bestStreak?'×'+this.bestStreak:'—';}
  controlHint(){return window.matchMedia('(pointer: coarse)').matches?'Slide your finger across the shape to slice.':'Click and drag your mouse across the shape to slice.';}
  readyHint(){return this.puzzle.kind==='targets'?'Aim through every marked dot.':this.puzzle.kind==='only'?'Leave the pale shape whole.':this.puzzle.zones?'Keep the full line away from the red region.':'You can also choose a start and end point with two taps or clicks.';}
  points(poly){return poly.map(p=>p.join(',')).join(' ');}
  polygon(poly,source=0){return `<polygon points="${this.points(poly)}" class="ss-shape ${this.puzzle.kind==='only'&&source!==this.puzzle.active?'ss-pale':''}"/>`;}
  load(){this.puzzle=this.puzzles[this.at];this.attempts=0;this.result=null;this.cancel();this.cursor=[200,170];this.$('cursor').setAttribute('visibility','hidden');this.$('round').textContent=`${String(this.at+1).padStart(2,'0')} / ${this.puzzles.length} · ${this.at<8?'First cuts':this.at<16?'Fresh angles':this.at<24?'Look closer':'A little ingenuity'}`;this.$('objective').textContent=this.puzzle.title;this.$('instruction').textContent=this.controlHint();this.$('zones').innerHTML=(this.puzzle.zones||[]).map(z=>`<polygon points="${this.points(z)}" class="ss-zone"/>`).join('');this.$('targets').innerHTML=(this.puzzle.targets||[]).map(p=>`<g><circle cx="${p[0]}" cy="${p[1]}" r="8" class="ss-target-ring"/><circle cx="${p[0]}" cy="${p[1]}" r="3" class="ss-target"/></g>`).join('');this.retry(false);this.stats();if(this.at===0&&!this.demoShown)this.demo();}
  feedback(title,detail,kind='ready'){this.$('verdict').textContent=title;this.$('detail').textContent=detail;this.$('feedback').dataset.kind=kind;}
  retry(focus=true){this.cancel();this.result=null;this.$('shapes').innerHTML=this.puzzle.polygons.map((p,i)=>this.polygon(p,i)).join('');this.$('hint').replaceChildren();this.$('line').setAttribute('visibility','hidden');this.$('retry').hidden=true;this.$('next').hidden=true;this.$('hintButton').hidden=false;this.$('note').textContent=this.attempts?'Your best cut counts. Try a new angle.':'No timer. No lives. Find your line.';this.feedback('Release to make your cut.',this.attempts?'Try another angle. You can improve your best cut.':this.readyHint());if(focus)this.board.focus({preventScroll:true});}
  drawLine(l,el=this.$('line')){if(!l)return;const d=[-l.n[1],l.n[0]];el.setAttribute('x1',l.a[0]-d[0]*650);el.setAttribute('y1',l.a[1]-d[1]*650);el.setAttribute('x2',l.a[0]+d[0]*650);el.setAttribute('y2',l.a[1]+d[1]*650);el.setAttribute('visibility','visible');}
  demo(){
    this.demoShown=true;
    if(window.matchMedia('(prefers-reduced-motion: reduce)').matches){this.hint(true);return;}
    this.demoActive=true;
    this.$('hint').innerHTML='<g class="ss-demo" aria-hidden="true"><line class="ss-demo-line" x1="100" y1="70" x2="300" y2="270"/><g class="ss-demo-pointer"><circle r="15"/><circle r="5"/></g></g>';
    this.$('shapes').classList.add('ss-demo-original');
    const pieces=this.G.split(this.puzzle.polygons[0],this.G.line([100,70],[300,270]));
    this.$('hint').insertAdjacentHTML('afterbegin',pieces.map((poly,i)=>`<g class="ss-demo-piece" style="--tx:${i===0?-8:8}px;--ty:${i===0?8:-8}px">${this.polygon(poly)}</g>`).join(''));
    this.feedback('Watch the cut → then try it','');
    this.demoTimer=setTimeout(()=>this.stopDemo(),2400);
    this.timers.push(this.demoTimer);
  }
  stopDemo(){
    if(!this.demoActive)return;
    clearTimeout(this.demoTimer);this.demoActive=false;
    this.$('shapes').classList.remove('ss-demo-original');this.$('hint').replaceChildren();
    this.feedback('Your turn',this.readyHint());
  }
  hint(first=false){this.stopDemo();const [a,b]=this.puzzle.solution;this.$('hint').innerHTML=`<line x1="${a[0]}" y1="${a[1]}" x2="${b[0]}" y2="${b[1]}" class="ss-hint ${first?'ss-first-hint':''}"/>`;if(!first)this.feedback('One possible cut',this.puzzle.hint||'Follow the dotted guide, or find another valid solution.');}
  point(e){const r=this.board.getBoundingClientRect();return [Math.max(0,Math.min(400,(e.clientX-r.left)*400/r.width)),Math.max(0,Math.min(340,(e.clientY-r.top)*340/r.height))];}
  down(e){if(this.result||this.complete||e.button!==0||!e.isPrimary)return;e.preventDefault();this.stopDemo();this.board.focus({preventScroll:true});this.pointer={id:e.pointerId,start:this.point(e),moved:false};this.board.setPointerCapture(e.pointerId);this.$('hint').replaceChildren();}
  move(e){if(!this.pointer||this.pointer.id!==e.pointerId)return;const p=this.point(e);if(this.G.distance(p,this.pointer.start)>5)this.pointer.moved=true;this.drawLine(this.G.line(this.tapStart||this.pointer.start,p));}
  up(e){if(!this.pointer||this.pointer.id!==e.pointerId)return;const p=this.point(e),gesture=this.pointer;this.pointer=null;if(gesture.moved){const a=this.tapStart||gesture.start;this.tapStart=null;this.submit(a,p);}else if(this.tapStart){const a=this.tapStart;this.tapStart=null;this.submit(a,p);}else{this.tapStart=p;this.cursor=p;this.showCursor();this.feedback('Choose the other end','Tap a second point to slice. Escape cancels.');}}
  cancel(){this.stopDemo();this.pointer=null;this.tapStart=null;this.$('line')?.setAttribute('visibility','hidden');}
  showCursor(){this.$('cursor').setAttribute('cx',this.cursor[0]);this.$('cursor').setAttribute('cy',this.cursor[1]);this.$('cursor').setAttribute('visibility','visible');}
  key(e){if(this.result||this.complete)return;this.stopDemo();const delta={ArrowLeft:[-1,0],ArrowRight:[1,0],ArrowUp:[0,-1],ArrowDown:[0,1]}[e.key];if(delta){e.preventDefault();const step=e.shiftKey?1:10;this.cursor=[Math.max(0,Math.min(400,this.cursor[0]+delta[0]*step)),Math.max(0,Math.min(340,this.cursor[1]+delta[1]*step))];this.showCursor();if(this.tapStart)this.drawLine(this.G.line(this.tapStart,this.cursor));}if(e.key==='Enter'||e.key===' '){e.preventDefault();if(this.tapStart){const a=this.tapStart;this.tapStart=null;this.submit(a,this.cursor);}else{this.tapStart=this.cursor.slice();this.showCursor();this.feedback('Start point set','Move the cursor with arrows. Enter slices; Shift + arrows makes fine adjustments.');}}if(e.key==='Escape'){this.cancel();this.$('cursor').setAttribute('visibility','hidden');this.feedback('Line cancelled','Draw again, or tap two points.');}}
  submit(a,b){if(this.result||this.complete)return;this.stopDemo();const r=this.M.evaluate(this.puzzle,a,b);this.result=r;this.attempts++;if(!this.started){this.started=true;this.emit('game_start');}const award=this.M.award(this.session,this.puzzle.id,r);this.session=award.state;this.best=Math.max(this.best,this.session.score);this.bestStreak=Math.max(this.bestStreak,this.session.bestStreak);this.save();this.stats();this.$('hint').replaceChildren();this.$('cursor').setAttribute('visibility','hidden');if(r.line)this.drawLine(r.line);
    if(r.pieces.length)this.$('shapes').innerHTML=r.pieces.map(piece=>{const shift=r.line?piece.side*10:0,n=r.line?.n||[0,0],center=this.G.centroid(piece.poly),area=this.G.area(piece.poly),total=this.G.area(this.puzzle.polygons[piece.source]);const label=['area','doubleArea','equalTriangles'].includes(this.puzzle.kind)?(100*area/total).toFixed(1)+'%':this.puzzle.kind==='sides'?piece.poly.length+' sides':'';return `<g class="ss-piece" style="--tx:${n[0]*shift}px;--ty:${n[1]*shift}px">${this.polygon(piece.poly,piece.source)}${label&&area>700?`<text class="ss-piece-label" x="${center[0]}" y="${center[1]}">${label}</text>`:''}</g>`;}).join('');
    const accuracy=r.metric?`${r.metric}: ${r.quality.toFixed(1).replace('.0','')}%. `:'';this.feedback(r.label||'TRY ANOTHER CUT',accuracy+r.message+(award.delta?` +${award.delta} points.`:''),r.pass?'success':'retry');this.$('retry').hidden=false;this.$('retry').textContent=r.pass?'Improve cut':'Try Again';this.$('hintButton').hidden=true;this.$('next').hidden=!r.pass;this.$('next').textContent=this.at===this.puzzles.length-1?'Finish →':'Next challenge →';this.$('note').textContent=r.pass?(award.delta?`+${award.delta} points${this.session.streak>=2?' · Strong cuts ×'+this.session.streak:''}`:'Your best score for this challenge is already saved.'):'No lives lost. The next try is yours.';
    if(r.pass){this.sound?.chain(Math.min(6,Math.max(1,this.session.streak)));this.$('pop').textContent=award.delta?'+'+award.delta:'✓';this.$('pop').classList.remove('is-active');void this.$('pop').offsetWidth;this.$('pop').classList.add('is-active');this.emit('level_complete',{level:this.puzzle.id,accuracy:r.quality});}else this.sound?.place();
  }
  next(){if(!this.result?.pass)return;if(this.at===this.puzzles.length-1){this.complete=true;this.$('complete').hidden=false;this.$('summary').textContent=`All ${this.puzzles.length} challenges solved. Score: ${this.session.score.toLocaleString()} · Best: ${this.best.toLocaleString()} · Best streak this round: ${this.session.bestStreak}.`;this.$('next').hidden=true;this.$('retry').hidden=true;this.$('complete').querySelector('h2').focus();this.emit('game_over',{score:this.session.score});return;}this.at++;this.load();this.board.focus({preventScroll:true});}
  destroy(){this.cancel();this.timers.forEach(clearTimeout);}
}
